tinyMCE.addI18n('es.advanced_dlg',{
about_title:"Acerca de TinyMCE",
about_general:"Acerca de ",
about_help:"Ayuda",
about_license:"Licencia",
about_plugins:"Complementos",
about_plugin:"Complemento",
about_author:"Autor",
about_version:"Version",
about_loaded:"Complementos cargados",
anchor_title:"Insertar/editar ancla",
anchor_name:"Nombre del ancla",
code_title:"Editor del codigo fuente HTML",
code_wordwrap:"Ajustar al margen",
colorpicker_title:"Seleccionar color",
colorpicker_picker_tab:"Paleta",
colorpicker_picker_title:"Paleta de color",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Paleta de colores",
colorpicker_named_tab:"Nombrados",
colorpicker_named_title:"Colores nombrados",
colorpicker_color:"Color:",
colorpicker_name:"Nombre:",
charmap_title:"Seleccionar caracter personalizado",
image_title:"Insertar/editar imagen",
image_src:"URL de la Imagen",
image_alt:"Descripcion de la Imagen",
image_list:"Lista de la Imagen",
image_border:"Borde",
image_dimensions:"Dimension",
image_vspace:"Espacio vertical",
image_hspace:"Espacio horizontal",
image_align:"Alineacion",
image_align_baseline:"Baseline",
image_align_top:"Arriba",
image_align_middle:"Medio",
image_align_bottom:"Debajo",
image_align_texttop:"Texto arriba",
image_align_textbottom:"Texto debajo",
image_align_left:"Izquierda",
image_align_right:"Derecha",
link_title:"Insertar/editar hipervinculo",
link_url:"URL del hipervinculo",
link_target:"Destino",
link_target_same:"Abrir vinculo en la misma ventana",
link_target_blank:"Abrir vinculo en una ventana nueva",
link_titlefield:"Titulo",
link_is_email:"La URL que ingreso parece ser una direccion de email, desea agregar el prefijo mailto: necesario?",
link_is_external:"La URL que ingreso parece ser un vinculo externo, desea agregar el prefijo http:// necesario?",
link_list:"Lista de hipervinculos"
});